-- Innkeeper schema. Portable across PostgreSQL 16+ and H2 2.x in PostgreSQL mode.
-- Conventions: snake_case, BIGINT identity keys, DATE for calendar days,
-- TIMESTAMP WITH TIME ZONE for instants, NUMERIC(10,2) for money,
-- explicit ON DELETE rules on every foreign key, CHECK constraints on every status column.

CREATE TABLE branch (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code          VARCHAR(16)  NOT NULL,
    name          VARCHAR(120) NOT NULL,
    tagline       VARCHAR(160) NOT NULL,
    description   VARCHAR(1000) NOT NULL,
    address_line  VARCHAR(200) NOT NULL,
    city          VARCHAR(80)  NOT NULL,
    state         VARCHAR(40)  NOT NULL,
    postal_code   VARCHAR(16)  NOT NULL,
    phone         VARCHAR(32)  NOT NULL,
    email         VARCHAR(160) NOT NULL,
    tax_rate      NUMERIC(5,4) NOT NULL,
    timezone      VARCHAR(64)  NOT NULL,
    created_at    TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_branch_code UNIQUE (code),
    CONSTRAINT ck_branch_tax_rate CHECK (tax_rate >= 0 AND tax_rate < 1)
);

CREATE TABLE room_type (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code           VARCHAR(16)  NOT NULL,
    name           VARCHAR(80)  NOT NULL,
    description    VARCHAR(600) NOT NULL,
    max_occupancy  INTEGER      NOT NULL,
    bed_setup      VARCHAR(80)  NOT NULL,
    sort_order     INTEGER      NOT NULL DEFAULT 0,
    CONSTRAINT uq_room_type_code UNIQUE (code),
    CONSTRAINT ck_room_type_occupancy CHECK (max_occupancy BETWEEN 1 AND 8)
);

CREATE TABLE room (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    branch_id     BIGINT       NOT NULL REFERENCES branch (id) ON DELETE CASCADE,
    room_type_id  BIGINT       NOT NULL REFERENCES room_type (id) ON DELETE RESTRICT,
    room_number   VARCHAR(8)   NOT NULL,
    floor         INTEGER      NOT NULL,
    nightly_rate  NUMERIC(10,2) NOT NULL,
    status        VARCHAR(16)  NOT NULL DEFAULT 'AVAILABLE',
    notes         VARCHAR(300),
    CONSTRAINT uq_room_branch_number UNIQUE (branch_id, room_number),
    CONSTRAINT ck_room_rate CHECK (nightly_rate > 0),
    CONSTRAINT ck_room_status CHECK (status IN ('AVAILABLE', 'OUT_OF_SERVICE'))
);

CREATE TABLE guest (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name  VARCHAR(80)  NOT NULL,
    last_name   VARCHAR(80)  NOT NULL,
    email       VARCHAR(160) NOT NULL,
    phone       VARCHAR(32),
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_guest_email_lower CHECK (email = LOWER(email))
);

CREATE INDEX ix_guest_email ON guest (email);

CREATE TABLE employee (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    branch_id   BIGINT       NOT NULL REFERENCES branch (id) ON DELETE CASCADE,
    first_name  VARCHAR(80)  NOT NULL,
    last_name   VARCHAR(80)  NOT NULL,
    email       VARCHAR(160) NOT NULL,
    position    VARCHAR(60)  NOT NULL,
    hired_on    DATE         NOT NULL,
    active      BOOLEAN      NOT NULL DEFAULT TRUE,
    CONSTRAINT uq_employee_email UNIQUE (email)
);

CREATE TABLE user_account (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username       VARCHAR(40)  NOT NULL,
    password_hash  VARCHAR(100) NOT NULL,
    role           VARCHAR(10)  NOT NULL,
    display_name   VARCHAR(120) NOT NULL,
    employee_id    BIGINT       REFERENCES employee (id) ON DELETE SET NULL,
    enabled        BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at     TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_user_account_username UNIQUE (username),
    CONSTRAINT uq_user_account_employee UNIQUE (employee_id),
    CONSTRAINT ck_user_account_role CHECK (role IN ('GUEST', 'STAFF', 'MANAGER'))
);

CREATE TABLE booking (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    confirmation_code  VARCHAR(12)  NOT NULL,
    room_id            BIGINT       NOT NULL REFERENCES room (id) ON DELETE RESTRICT,
    guest_id           BIGINT       NOT NULL REFERENCES guest (id) ON DELETE RESTRICT,
    check_in_date      DATE         NOT NULL,
    check_out_date     DATE         NOT NULL,
    adults             INTEGER      NOT NULL,
    children           INTEGER      NOT NULL DEFAULT 0,
    special_requests   VARCHAR(500),
    status             VARCHAR(16)  NOT NULL,
    nightly_rate       NUMERIC(10,2) NOT NULL,
    cancellation_fee   NUMERIC(10,2) NOT NULL DEFAULT 0,
    version            BIGINT        NOT NULL DEFAULT 0,
    created_at         TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    checked_in_at      TIMESTAMP WITH TIME ZONE,
    checked_out_at     TIMESTAMP WITH TIME ZONE,
    cancelled_at       TIMESTAMP WITH TIME ZONE,
    CONSTRAINT uq_booking_code UNIQUE (confirmation_code),
    CONSTRAINT ck_booking_dates CHECK (check_out_date > check_in_date),
    CONSTRAINT ck_booking_adults CHECK (adults BETWEEN 1 AND 8),
    CONSTRAINT ck_booking_children CHECK (children BETWEEN 0 AND 8),
    CONSTRAINT ck_booking_status CHECK (status IN ('CONFIRMED', 'CHECKED_IN', 'CHECKED_OUT', 'CANCELLED')),
    CONSTRAINT ck_booking_rate CHECK (nightly_rate > 0),
    CONSTRAINT ck_booking_cancellation_fee CHECK (cancellation_fee >= 0)
);

CREATE INDEX ix_booking_guest ON booking (guest_id);
CREATE INDEX ix_booking_room ON booking (room_id);
CREATE INDEX ix_booking_check_in ON booking (check_in_date);
CREATE INDEX ix_booking_check_out ON booking (check_out_date);

-- One row per night a booking holds a room. The unique constraint is the double-booking guard.
CREATE TABLE room_night (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_id     BIGINT NOT NULL REFERENCES room (id) ON DELETE CASCADE,
    night_date  DATE   NOT NULL,
    booking_id  BIGINT NOT NULL REFERENCES booking (id) ON DELETE CASCADE,
    CONSTRAINT uq_room_night UNIQUE (room_id, night_date)
);

CREATE INDEX ix_room_night_booking ON room_night (booking_id);
CREATE INDEX ix_room_night_date ON room_night (night_date);

CREATE TABLE invoice (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id        BIGINT        NOT NULL REFERENCES booking (id) ON DELETE CASCADE,
    tax_rate          NUMERIC(5,4)  NOT NULL,
    room_subtotal     NUMERIC(10,2) NOT NULL,
    tax               NUMERIC(10,2) NOT NULL,
    fines             NUMERIC(10,2) NOT NULL DEFAULT 0,
    cancellation_fee  NUMERIC(10,2) NOT NULL DEFAULT 0,
    total             NUMERIC(10,2) NOT NULL,
    status            VARCHAR(16)   NOT NULL,
    issued_at         TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at        TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_invoice_booking UNIQUE (booking_id),
    CONSTRAINT ck_invoice_status CHECK (status IN ('OPEN', 'PAID', 'VOID'))
);

CREATE TABLE invoice_line (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id   BIGINT        NOT NULL REFERENCES invoice (id) ON DELETE CASCADE,
    line_order   INTEGER       NOT NULL,
    kind         VARCHAR(20)   NOT NULL,
    description  VARCHAR(200)  NOT NULL,
    quantity     INTEGER       NOT NULL,
    unit_amount  NUMERIC(10,2) NOT NULL,
    amount       NUMERIC(10,2) NOT NULL,
    CONSTRAINT ck_invoice_line_kind CHECK (kind IN ('ROOM_NIGHTS', 'TAX', 'FINE', 'CANCELLATION_FEE')),
    CONSTRAINT ck_invoice_line_quantity CHECK (quantity > 0)
);

CREATE INDEX ix_invoice_line_invoice ON invoice_line (invoice_id);

CREATE TABLE payment (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id               BIGINT        NOT NULL REFERENCES invoice (id) ON DELETE CASCADE,
    amount                   NUMERIC(10,2) NOT NULL,
    method                   VARCHAR(16)   NOT NULL,
    reference                VARCHAR(64),
    paid_at                  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    recorded_by_employee_id  BIGINT        REFERENCES employee (id) ON DELETE SET NULL,
    CONSTRAINT ck_payment_amount CHECK (amount > 0),
    CONSTRAINT ck_payment_method CHECK (method IN ('CARD', 'CASH'))
);

CREATE INDEX ix_payment_invoice ON payment (invoice_id);

CREATE TABLE fine (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id             BIGINT        NOT NULL REFERENCES booking (id) ON DELETE CASCADE,
    reason                 VARCHAR(200)  NOT NULL,
    amount                 NUMERIC(10,2) NOT NULL,
    issued_at              TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    issued_by_employee_id  BIGINT        REFERENCES employee (id) ON DELETE SET NULL,
    CONSTRAINT ck_fine_amount CHECK (amount > 0)
);

CREATE INDEX ix_fine_booking ON fine (booking_id);

CREATE TABLE booking_event (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id   BIGINT       NOT NULL REFERENCES booking (id) ON DELETE CASCADE,
    event_type   VARCHAR(24)  NOT NULL,
    occurred_at  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    actor        VARCHAR(80)  NOT NULL,
    note         VARCHAR(300),
    CONSTRAINT ck_booking_event_type CHECK (event_type IN
        ('CREATED', 'CHECKED_IN', 'CHECKED_OUT', 'CANCELLED', 'FINE_ADDED', 'PAYMENT_RECORDED'))
);

CREATE INDEX ix_booking_event_booking ON booking_event (booking_id);

CREATE TABLE maintenance_team (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    branch_id      BIGINT       NOT NULL REFERENCES branch (id) ON DELETE CASCADE,
    name           VARCHAR(80)  NOT NULL,
    specialty      VARCHAR(80)  NOT NULL,
    contact_email  VARCHAR(160) NOT NULL,
    CONSTRAINT uq_maintenance_team_name UNIQUE (branch_id, name)
);

CREATE TABLE maintenance_request (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    branch_id     BIGINT        NOT NULL REFERENCES branch (id) ON DELETE CASCADE,
    room_id       BIGINT        REFERENCES room (id) ON DELETE SET NULL,
    title         VARCHAR(120)  NOT NULL,
    description   VARCHAR(1000) NOT NULL,
    priority      VARCHAR(10)   NOT NULL,
    status        VARCHAR(16)   NOT NULL,
    team_id       BIGINT        REFERENCES maintenance_team (id) ON DELETE SET NULL,
    reported_by   VARCHAR(80)   NOT NULL,
    created_at    TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    started_at    TIMESTAMP WITH TIME ZONE,
    completed_at  TIMESTAMP WITH TIME ZONE,
    CONSTRAINT ck_maintenance_priority CHECK (priority IN ('LOW', 'NORMAL', 'URGENT')),
    CONSTRAINT ck_maintenance_status CHECK (status IN ('OPEN', 'IN_PROGRESS', 'DONE'))
);

CREATE INDEX ix_maintenance_request_branch_status ON maintenance_request (branch_id, status);

CREATE TABLE inventory_item (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    branch_id      BIGINT      NOT NULL REFERENCES branch (id) ON DELETE CASCADE,
    name           VARCHAR(80) NOT NULL,
    category       VARCHAR(40) NOT NULL,
    quantity       INTEGER     NOT NULL,
    reorder_level  INTEGER     NOT NULL,
    unit           VARCHAR(20) NOT NULL,
    updated_at     TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_inventory_item_name UNIQUE (branch_id, name),
    CONSTRAINT ck_inventory_quantity CHECK (quantity >= 0),
    CONSTRAINT ck_inventory_reorder_level CHECK (reorder_level >= 0)
);

CREATE TABLE parking_space (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    branch_id     BIGINT     NOT NULL REFERENCES branch (id) ON DELETE CASCADE,
    space_number  VARCHAR(8) NOT NULL,
    kind          VARCHAR(8) NOT NULL,
    booking_id    BIGINT     REFERENCES booking (id) ON DELETE SET NULL,
    CONSTRAINT uq_parking_space_number UNIQUE (branch_id, space_number),
    CONSTRAINT uq_parking_space_booking UNIQUE (booking_id),
    CONSTRAINT ck_parking_kind CHECK (kind IN ('GUEST', 'STAFF'))
);

CREATE TABLE complaint (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    branch_id        BIGINT        NOT NULL REFERENCES branch (id) ON DELETE CASCADE,
    booking_id       BIGINT        REFERENCES booking (id) ON DELETE SET NULL,
    ticket_number    VARCHAR(12)   NOT NULL,
    guest_name       VARCHAR(160)  NOT NULL,
    guest_email      VARCHAR(160)  NOT NULL,
    category         VARCHAR(20)   NOT NULL,
    description      VARCHAR(2000) NOT NULL,
    status           VARCHAR(16)   NOT NULL DEFAULT 'OPEN',
    resolution_note  VARCHAR(1000),
    created_at       TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    resolved_at      TIMESTAMP WITH TIME ZONE,
    CONSTRAINT uq_complaint_ticket UNIQUE (ticket_number),
    CONSTRAINT ck_complaint_category CHECK (category IN ('ROOM', 'SERVICE', 'NOISE', 'BILLING', 'OTHER')),
    CONSTRAINT ck_complaint_status CHECK (status IN ('OPEN', 'IN_PROGRESS', 'RESOLVED'))
);

CREATE INDEX ix_complaint_branch_status ON complaint (branch_id, status);

CREATE TABLE app_metadata (
    meta_key    VARCHAR(40)  NOT NULL PRIMARY KEY,
    meta_value  VARCHAR(200) NOT NULL,
    updated_at  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE room_night IS 'One row per (room, night) held by a booking; UNIQUE (room_id, night_date) prevents double booking.';
COMMENT ON TABLE booking_event IS 'Append-only audit trail of booking transitions.';
